config/routes.rb
TweetThat::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/network/:id', :to => 'users#network'
  
  root :to => 'pages#home'

end

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h4 class="micropost">Say anything:</h4>
        <%= render 'shared/micropost_form' %>
    <h3>Recent tweets</h3>
		<%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
				<%= render 'shared/stats' %>
      </td>
    </tr>
  </table>
<% else %>
  <p>
    Come join us and start tweeting to the world!
  </p>

  <%= link_to "Create new user", signup_path, :class => "signup_button round" %>
  <h4><center><br>Already a user? <%= link_to "Sign in", signin_path %> immediately!</center><h4>
<% end %>